    #AutoDetect=nvml
    NodeName = michman498212ab-44e5-4eb7-99c9-b042df4caf42 Name=gpu Type=GA100 File=/dev/nvidia0

    #NodeName = michmanc3ab4d15-3d62-4d03-879d-011ddbd7f6f3 Name=gpu Type=1g.10gb File=/dev/nvidia-caps/nvidia-cap102,/dev/nvidia-caps/nvidia-cap103
    #NodeName = michmanc3ab4d15-3d62-4d03-879d-011ddbd7f6f3 Name=gpu Type=1g.10gb File=/dev/nvidia-caps/nvidia-cap111,/dev/nvidia-caps/nvidia-cap112
    #NodeName = michmanc3ab4d15-3d62-4d03-879d-011ddbd7f6f3 Name=gpu Type=1g.10gb File=/dev/nvidia-caps/nvidia-cap120,/dev/nvidia-caps/nvidia-cap121
    #NodeName = michmanc3ab4d15-3d62-4d03-879d-011ddbd7f6f3 Name=gpu Type=1g.10gb File=/dev/nvidia-caps/nvidia-cap66,/dev/nvidia-caps/nvidia-cap67
    #NodeName = michmanc3ab4d15-3d62-4d03-879d-011ddbd7f6f3 Name=gpu Type=1g.10gb File=/dev/nvidia-caps/nvidia-cap75,/dev/nvidia-caps/nvidia-cap76
    #NodeName = michmanc3ab4d15-3d62-4d03-879d-011ddbd7f6f3 Name=gpu Type=1g.10gb File=/dev/nvidia-caps/nvidia-cap84,/dev/nvidia-caps/nvidia-cap85
    #NodeName = michmanc3ab4d15-3d62-4d03-879d-011ddbd7f6f3 Name=gpu Type=1g.10gb File=/dev/nvidia-caps/nvidia-cap93,/dev/nvidia-caps/nvidia-cap94
    
    
    ##### 1g.20Gb
    NodeName = michmanc3ab4d15-3d62-4d03-879d-011ddbd7f6f3 Name=gpu Type=1g.20gb File=/dev/nvidia-caps/nvidia-cap30,/dev/nvidia-caps/nvidia-cap31
    NodeName = michmanc3ab4d15-3d62-4d03-879d-011ddbd7f6f3 Name=gpu Type=1g.20gb File=/dev/nvidia-caps/nvidia-cap39,/dev/nvidia-caps/nvidia-cap40
    NodeName = michmanc3ab4d15-3d62-4d03-879d-011ddbd7f6f3 Name=gpu Type=1g.20gb File=/dev/nvidia-caps/nvidia-cap48,/dev/nvidia-caps/nvidia-cap49
    NodeName = michmanc3ab4d15-3d62-4d03-879d-011ddbd7f6f3 Name=gpu Type=1g.20gb File=/dev/nvidia-caps/nvidia-cap57,/dev/nvidia-caps/nvidia-cap58
    
    
    #NodeName = michmanc3ab4d15-3d62-4d03-879d-011ddbd7f6f3 Name=gpu Type=GA100 File=/dev/nvidia0
