#Configuration file for slurm PUPUPU
#Authentification
AuthType=auth/munge

AuthAltTypes=auth/jwt
AuthAltParameters=jwt_key=/etc/slurm/jwt_hs256.key

#The accounting storage mechanism type.
AccountingStorageType= accounting_storage/slurmdbd

AccountingStorageTRES=gres/gpu,gres/shard,gres/gpu:1g.20gb

#The name of the machine hosting the accounting storage database.
AccountingStorageHost= michman7ce85f85-9cbb-4b3e-ad27-be9a0fc36db0

#The name by which this Slurm managed cluster is known in the accounting database. 
ClusterName= MLM-a100

#Hostname of the machine where Slurm control daemon is executed
ControlMachine= michman2588e870-1045-48a1-9fa6-82daee6e65b5

SlurmctldDebug=debug5

SlurmdDebug=debug5

#Identifies the type of resource selection algorithm to be used.
#select/cons_tres - the resources (cores, memory, GPUs and all other trackable resources) within a node are individually allocated as consumable resources. 
SelectType = select/cons_tres

#Parameters for SelectType
SelectTypeParameters= CR_CPU_Memory

DefMemPerCPU=100

#Identifies the type of task launch plugin, typically used to provide resource management within a node 
TaskPlugin = task/affinity,task/cgroup

PlugStackConfig = /etc/slurm/plugstack.conf.d/pyxis.conf

PriorityType=priority/multifactor

GresTypes=gpu

#Optional parameters for the task plugin.
TaskPluginParam= Cores

ProctrackType=proctrack/cgroup

Epilog=/home/michman/dockerf/epilog.sh

JobAcctGatherType= jobacct_gather/cgroup

#If set to "ALL" then jobs which exceed a partition's size and/or time limits will be rejected at submission time. 
#If job is submitted to multiple partitions, the job must satisfy the limits on all the requested partitions.
EnforcePartLimits= ALL

#Controls when a DOWN node will be returned to service. 
# 1  means,  DOWN node will become available for use upon registration with a valid configuration only if it was set DOWN due to being non-responsive. 
#For any other reason, its state will not automatically be changed. 
ReturnToService= 1

#Identifies the type of scheduler to be used.
#For a backfill scheduling module to augment the default FIFO scheduling. 
#Backfill scheduling will initiate lower-priority jobs if doing so does not delay the expected initiation time of any higher priority job.
SchedulerType= sched/backfill
SchedulerParameters=defer
#Pathname of a file into which the slurmctld daemon's logs are written.
SlurmctldLogFile= /var/log/slurm/slurmctld.log

#Pathname of a file into which the slurmctld daemon may write its process id. 
SlurmctldPidFile= /var/run/slurm/slurmctld.pid

#Pathname of a file into which the slurmd daemon's logs are written. 
SlurmdLogFile= /var/log/slurm/slurmd.log

#Pathname of a file into which the slurmd daemon may write its process id. 
SlurmdPidFile= /var/run/slurm/slurmd.pid

#Pathname of a directory into which the slurmd daemon's state information 
#and batch job script information are written.
SlurmdSpoolDir= /var/spool/slurm/d

#Pathname of a directory into which the Slurm controller, slurmctld, saves its state.
#Slurm state will be saved here to recover from system failures.
StateSaveLocation= /var/spool/slurm/ctld

#Nodes 
#CPUs - number of logical processors on the node.
#RealMemory - size of real memory on the node in megabytes. Parameter is going to be set, if memory is consumable resource.


NodeName = michman498212ab-44e5-4eb7-99c9-b042df4caf42 CPUs=14 RealMemory=117964 Gres=gpu:GA100:1
NodeName = michmanc3ab4d15-3d62-4d03-879d-011ddbd7f6f3 CPUs=14 RealMemory=117964 Gres=gpu:1g.20gb:4
#Partition
#PartitionName=main Nodes = "michman498212ab-44e5-4eb7-99c9-b042df4caf42, michmanc3ab4d15-3d62-4d03-879d-011ddbd7f6f3" Default=YES
#PartitionName=main Nodes = "michmanc3ab4d15-3d62-4d03-879d-011ddbd7f6f3" Default= YES
PartitionName=cpu Nodes = "michman498212ab-44e5-4eb7-99c9-b042df4caf42" Default= No
PartitionName=gpu Nodes = "michmanc3ab4d15-3d62-4d03-879d-011ddbd7f6f3" Default= Yes